[package]
name = "aoc02"
version = "0.1.0"
authors = ["CJ <cjting1128@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
